---

ansible_host: localhost
ansible_connection: local

build:
  NAME: ci-for-labs-ci-cd
  PIPELINE_SOURCE_REPOSITORY_REF: cleanup
  PIPELINE_SOURCE_REPOSITORY_URL: https://github.com/pcarney8/labs-ci-cd.git
  RUN_POLICY: Parallel

openshift_cluster_content:
- object: ci-for-labs-ci-cd
  content:
  - name: pipeline
    template: "https://raw.githubusercontent.com/rht-labs/openshift-templates/v1.0/jenkins-pipelines/jenkins-pipeline-no-ocp-triggers-template.yml"
    params_from_vars: "{{ build }}"
    namespace: "{{ ci_cd_namespace }}"
    tags:
    - ci
