---
# TODO There is probably a way to genericize these tasks so they need to be defined once for labs & redhat

- name: Check For Existing Script
  uri:
    url: "https://{{ nexus_url }}/service/siesta/rest/v1/script/{{ nexus_redhat_script_name }}"
    method: GET
    user: "{{ nexus_user }}"
    password: "{{ nexus_password }}"
    force_basic_auth: yes
    status_code: 200,404
  register: get_script_result

- name: Delete Script if it Exists
  uri:
    url: "https://{{ nexus_url }}/service/siesta/rest/v1/script/{{ nexus_redhat_script_name }}"
    method: DELETE
    user: "{{ nexus_user }}"
    password: "{{ nexus_password }}"
    force_basic_auth: yes
    status_code: 204
  when: get_script_result.status == 200

- name: Create New Script
  uri:
    url: "https://{{ nexus_url }}/service/siesta/rest/v1/script/"
    method: POST
    user: "{{ nexus_user }}"
    password: "{{ nexus_password }}"
    body_format: json
    body: "{{ lookup('file', nexus_redhat_script_file )}}"
    force_basic_auth: yes
    status_code: 204

- name: Execute New Script
  uri:
    url: "https://{{ nexus_url }}/service/siesta/rest/v1/script/{{ nexus_redhat_script_name }}/run"
    method: POST
    user: "{{ nexus_user }}"
    password: "{{ nexus_password }}"
    HEADER_Content-Type: "text/plain"
    force_basic_auth: yes
    status_code: 200   
