---
openshift_cluster_content:
- object: projectrequest
  content:
  - name: ci-cd
    template: "https://raw.githubusercontent.com/redhat-cop/cluster-lifecycle/master/files/projectrequest/template.yml"
    template_action: create
    params: "{{ inventory_dir }}/../params/projectrequests/ci-cd"
    tags:
    - projects
  - name: dev
    template: "https://raw.githubusercontent.com/redhat-cop/cluster-lifecycle/master/files/projectrequest/template.yml"
    template_action: create
    params: "{{ inventory_dir }}/../params/projectrequests/dev"
    tags:
    - projects
  - name: demo
    template: "https://raw.githubusercontent.com/redhat-cop/cluster-lifecycle/master/files/projectrequest/template.yml"
    template_action: create
    params: "{{ inventory_dir }}/../params/projectrequests/demo"
    tags:
    - projects
- object: ci-cd-builds
  content:
  - name: jenkins-s2i
    template: "{{ inventory_dir }}/../openshift-templates/jenkins-s2i-build/template.yaml"
    params: "{{ inventory_dir }}/../params/jenkins/build"
    namespace: labs-ci-cd
    tags:
    - jenkins
  - name: jenkins-slave-ansible
    template: "{{ inventory_dir }}/../openshift-templates/jenkins-slave-pod/template.json"
    params: "{{ inventory_dir }}/../params/jenkins-slave-ansible/build"
    namespace: labs-ci-cd
    tags:
    - jenkins-slaves
  - name: jenkins-slave-mvn
    template: "{{ inventory_dir }}/../openshift-templates/jenkins-slave-pod/template.json"
    params: "{{ inventory_dir }}/../params/jenkins-slave-mvn/build"
    namespace: labs-ci-cd
    tags:
    - jenkins-slaves
  - name: jenkins-slave-npm
    template: "{{ inventory_dir }}/../openshift-templates/jenkins-slave-pod/template.json"
    params: "{{ inventory_dir }}/../params/jenkins-slave-npm/build"
    namespace: labs-ci-cd
    tags:
    - jenkins-slaves
  - name: jenkins-slave-zap
    template: "{{ inventory_dir }}/../openshift-templates/jenkins-slave-pod/template.json"
    params: "{{ inventory_dir }}/../params/jenkins-slave-zap/build"
    namespace: labs-ci-cd
    tags:
    - jenkins-slaves
  - name: jenkins-slave-ansible
    template: "{{ inventory_dir }}/../openshift-templates/jenkins-slave-pod/template.json"
    params: "{{ inventory_dir }}/../params/jenkins-slave-ansible/build"
    namespace: labs-ci-cd
    tags:
      - jenkins-slaves
      - ansible-slave
  - name: tool-box
    template: "{{ inventory_dir }}/../openshift-templates/docker-build/template.yaml"
    params: "{{ inventory_dir }}/../params/tool-box/build"
    namespace: labs-ci-cd
    tags:
      - tool-box
  - name: hoverfly
    template: "{{ inventory_dir }}/../openshift-templates/docker-build/template.yaml"
    params: "{{ inventory_dir }}/../params/hoverfly/build"
    namespace: labs-ci-cd
    tags:
      - hoverfly
- object: ci-cd-deployments
  content:
  - name: jenkins-persistent
    template: "{{ inventory_dir }}/../openshift-templates/jenkins/jenkins-persistent-template.yaml"
    params: "{{ inventory_dir }}/../params/jenkins/deploy"
    namespace: labs-ci-cd
    tags:
    - jenkins
  - name: nexus
    template: "{{ inventory_dir }}/../openshift-templates/nexus/template.json"
    params: "{{ inventory_dir }}/../params/nexus/deploy"
    namespace: labs-ci-cd
    tags:
    - nexus
  - name: sonarqube
    template: "{{ inventory_dir }}/../openshift-templates/sonarqube/template.json"
    params: "{{ inventory_dir }}/../params/sonarqube/build-and-deploy"
    namespace: labs-ci-cd
    tags:
    - sonar
  - name: sonarqube-postgresql
    template: "openshift//postgresql-persistent"
    params: "{{ inventory_dir }}/../params/sonarqube/postgresql"
    namespace: labs-ci-cd
    tags:
    - sonar
  - name: hoverfly
    template: "{{ inventory_dir }}/../openshift-templates/hoverfly/template.yaml"
    params: "{{ inventory_dir }}/../params/hoverfly/deploy"
    namespace: labs-ci-cd
    tags:
    - hoverfly
- object: app-builds
  content:
  - name: java-app-build
    template: "{{ inventory_dir }}/../openshift-templates/s2i-app-build/template-no-secrets.json"
    params: "{{ inventory_dir }}/../params/java-app/build"
    namespace: labs-ci-cd
- object: dev-stage
  content:
  - name: java-app
    template: "{{ inventory_dir }}/../openshift-templates/automation-api-hsql/template.json"
    params: "{{ inventory_dir }}/../params/java-app/deploy_dev"
    namespace: labs-dev
    tags:
    - java-app
  - name: fabric8-rolebinding
    template: "{{ inventory_dir }}/../openshift-templates/fabric8-role-bindings/template.json"
    params: "{{ inventory_dir }}/../params/java-app/fabric8_dev"
    namespace: labs-dev
    tags:
    - java-app
- object: demo-stage
  content:
  - name: java-app
    template: "{{ inventory_dir }}/../openshift-templates/automation-api-hsql/template.json"
    params: "{{ inventory_dir }}/../params/java-app/deploy_demo"
    namespace: labs-demo
    tags:
    - java-app
  - name: fabric8-rolebinding
    template: "{{ inventory_dir }}/../openshift-templates/fabric8-role-bindings/template.json"
    params: "{{ inventory_dir }}/../params/java-app/fabric8_demo"
    namespace: labs-demo
    tags:
    - java-app
- object: ci-for-labs-ci-cd
  content:
  - name: pipeline
    template: "{{ inventory_dir }}/../openshift-templates/jenkins-pipeline-no-ocp-triggers/template.yaml"
    params: "{{ inventory_dir }}/../params/ci-for-labs-ci-cd/build"
    namespace: labs-ci-cd
    tags:
    - ci
